site_name: intracranial_ephys_utils
docs_dir: docs
theme:
  name: material
  logo: assets/logo_3.png
  favicon: assets/favicon_3.ico
  palette:
    primary: red
  features:
    - toc.integrate

plugins:
  - mkdocstrings:
      handlers:
        python:
          options:
            members_order: source
  - search

nav:
  - Intracranial_Ephys_Utils: index.md
  - Documentation:
    - 'Loading data': 'documentation/load_data.md'
    - 'Look at data': 'documentation/manual_process.md'