site_name: intracranial_ephys_utils
docs_dir: docs
theme:
  name: material
  logo: assets/logo_3.png
  favicon: assets/favicon_3.ico
  palette:
    primary: red

plugins:
  - mkdocstrings:
      handlers:
        python:
          options:
            members_order: source
  - search

nav:
  - Intracranial_Ephys_Utils: index.md
  - References: reference.md