site_name: intracranial_ephys_utils
docs_dir: docs
theme:
  name: material
  logo: assets/logo.jpg
  favicon: assets/favicon.ico

plugins:
  - mkdocstrings

nav:
  - Intracranial_Ephys_Utils: index.md
  - References: reference.md